const express = require("express");
const router = express.Router();

const schoolRoute = require("./routes/school.router");  
const roleRoute = require("./routes/role.router");
const adminRoute = require("./routes/admin.router");
const userRoute = require("./routes/user.router");
const gradeRouter = require('./routes/grade.router');
const sectionRouter = require('./routes/section.router');
const applicationsslcRouter = require('./routes/applicationsslc.router');
const applicationhscRouter = require('./routes/applicationhsc.router');
const groupRouter = require('./routes/group.router');
const studentsslcRouter = require('./routes/studentsslc.router');
const studenthscRouter = require('./routes/studenthsc.router');
const subjectRouter = require('./routes/subject.router');
const sidebarpermissionsRouterRouter = require('./routes/sidebarpermissions.router');
const raiseFeeDemandRouter = require("./routes/RaiseFeeDemand.router");
const feeCollectionRouter = require("./routes/Feecollection.router");
const bulkUploadRouter = require('./routes/bulkupload.router');
const tcRouter = require("./routes/tc.router");
const tchscRouter = require("./routes/tchsc.router");
const attendanceSslcRouter = require("./routes/attendancesslc.router");
const eventRouter = require("./routes/event.router");
const attendanceHscRouter = require("./routes/attendancehsc.router");
const instructorRouter = require("./routes/instructor.router");
const studyplanRouter = require("./routes/studyplan.router");
const teacherallocationRouter = require("./routes/teacherAllocation.router");
const timesetRouter = require("./routes/timeSet.router");
const weekdayRouter = require("./routes/weekDay.router");
const timetableRouter = require("./routes/timeTable.router");


router.use("/timetable", timetableRouter);
router.use("/weekday", weekdayRouter);
router.use("/timeset", timesetRouter);
router.use("/teacherallocation", teacherallocationRouter);
router.use("/studyplan", studyplanRouter);
router.use("/instructor", instructorRouter);
router.use("/attendancehsc", attendanceHscRouter);
router.use("/event", eventRouter);
router.use("/attendance", attendanceSslcRouter);
router.use("/tchsc", tchscRouter);
router.use("/tc", tcRouter);
router.use("/user", userRoute);
router.use("/school", schoolRoute);  
router.use("/role", roleRoute);
router.use("/admin", adminRoute);
router.use('/grade', gradeRouter);
router.use('/section', sectionRouter);
router.use("/applicationsslc", applicationsslcRouter);
router.use("/applicationhsc", applicationhscRouter);
router.use("/group", groupRouter);
router.use("/studentsslc", studentsslcRouter);
router.use("/studenthsc", studenthscRouter);
router.use('/subject', subjectRouter);
router.use('/sidebar-permissions', sidebarpermissionsRouterRouter);
router.use('/raiseFeeDemand', raiseFeeDemandRouter);
router.use('/feeCollection', feeCollectionRouter);
router.use("/bulkupload", bulkUploadRouter);

module.exports = router;
